=== mekdjamel/master-info-lyon1-lance-matheossian/trunk/MIF13/TP1/XML/CVETU.dtd
<!ELEMENT CVETU (Entete, (Rubrique1|Rubrique2)+)>
<!ELEMENT Entete (Etudiant, Titre)>
<!ELEMENT Etudiant (Nom, Prenom, Adresse+, Telephone?, Email?, Photo?)>
<!ATTLIST Etudiant
					Numero CDATA #REQUIRED
					Formation CDATA #FIXED "M1 informatique">
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Adresse (#PCDATA)>
<!-- Le fait de pouvoir entrer plusieurs elements Adresse est destine a permettre une adresse sur plusieurs ligne, chacune dans un element different -->
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Photo (#PCDATA)>
<!ELEMENT Titre (#PCDATA)>
<!ELEMENT Rubrique1 (Item+)>
<!ATTLIST Rubrique1
					Titre (Formation|Experience) #REQUIRED>
<!ELEMENT Rubrique2 (Item+)>
<!ATTLIST Rubrique2
					Titre (Competences|Divers) #REQUIRED>
<!ELEMENT Item ((Date, Contenu1)|(SousTitre, Contenu1+)|(SousTitre, Contenu2+)|(Date, Contenu1))>
<!-- Ici, le premier type d'item est destine aux rubriques Formation et Experience et le second type aux deux autres. -->
<!ELEMENT Date (#PCDATA)>
<!ELEMENT SousTitre (#PCDATA)>
<!ELEMENT Contenu1 (#PCDATA)>
<!ELEMENT Contenu2 (#PCDATA)>

=== mekdjamel/master-info-lyon1-lance-matheossian/trunk/MIF13/TP1/dtd + xml/CVETU.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!DOCTYPE CVETU SYSTEM "CVETU.dtd">
<CVETU>
<Entete>
<Etudiant Numero="000012">
<Nom>Mathéossian
</Nom>
<Prenom>Dimitri
</Prenom>
<Adresse>50 avenue ! 
</Adresse>
<Adresse>69450 Décines
</Adresse>
<Telephone>+33 4 00 00 00 00
</Telephone>
<Email>dimitri.matheossian@etu.univ-lyon1.fr
</Email>
</Etudiant>
<Titre>Great Etudiant Dimitri
</Titre>
</Entete>
<Rubrique1 Titre="Formation">
<Item>
<Date>2010
</Date>
<Contenu1>  	Prestataire Intégrateur Webdeveloppeur
</Contenu1>
</Item>
</Rubrique1>
<Rubrique2 Titre="Competences">
<Item>
<SousTitre>Langages informatiques
</SousTitre>
<Contenu2>XHTML/CSS
</Contenu2>
<Contenu2>C++/C/JAVA/
</Contenu2>
</Item>
</Rubrique2>
</CVETU>
