=== mekdjamel/master-info-lyon1-lance-matheossian/trunk/MIF13/TP1/XSLT/CV.dtd
<!ELEMENT CV (Entete, Rubrique+)>
<!ELEMENT Entete (Etudiant, Titre)>
<!ELEMENT Etudiant (Nom, Prenom, Adresse+, Telephone?, Email?, Photo?)>
<!ATTLIST Etudiant
					Numero CDATA #REQUIRED
					Stages CDATA #FIXED "M1 informatique">
<!ELEMENT Nom (#PCDATA)>
<!ELEMENT Prenom (#PCDATA)>
<!ELEMENT Adresse (#PCDATA)>
<!-- Le fait de pouvoir entrer plusieurs elements Adresse est destine a permettre une adresse sur plusieurs ligne, chacune dans un element different -->
<!ELEMENT Telephone (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ELEMENT Photo (#PCDATA)>
<!ELEMENT Titre (#PCDATA)>
<!ELEMENT Rubrique (Item+)>
<!ATTLIST Rubrique
					Titre (Stages|Experience|Competences|Divers) #REQUIRED>
<!ELEMENT Item ((Date, Contenu)|(SousTitre, Contenu+))>
<!-- Ici, le premier type d'item est destine aux rubriques Formation et Experience et le second type aux deux autres. -->
<!ELEMENT Date (#PCDATA)>
<!ELEMENT SousTitre (#PCDATA)>
<!ELEMENT Contenu (#PCDATA)>

=== mekdjamel/master-info-lyon1-lance-matheossian/trunk/MIF13/TP1/XSLT/CV.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no" ?>
<!DOCTYPE CV SYSTEM "CV.dtd">
<CV>
	<Entete>
		<Etudiant Numero="10604950">
			<Nom>Mathéossian
			</Nom>
			<Prenom>Dimitri
			</Prenom>
			<Adresse>50 avenue ! 
			</Adresse>
			<Adresse>69150 Décines
			</Adresse>
			<Telephone>+33 4 00 00 00 00
			</Telephone>
			<Email>dimitri.matheossian@etu.univ-lyon1.fr
			</Email>
		</Etudiant>
		<Titre>Curriculum vitae
		</Titre>
	</Entete>
	<Rubrique Titre="Stages">
		<Item>
			<Date>2010
			</Date>
			<Contenu>  Intégrateur Webdeveloppeur
			</Contenu>
		</Item>
	</Rubrique>
	<Rubrique Titre="Competences">
		<Item>
			<SousTitre>Langages informatiques
			</SousTitre>
			<Contenu>XHTML/CSS
			</Contenu>
			<Contenu>C++/C/JAVA/
			</Contenu>
		</Item>
	</Rubrique>
</CV>
