=== mekdjamel/master-info-lyon1-lance-matheossian/trunk/MIF13/TP1/Rendu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:annotation>
		<xs:documentation>
		Ce schema presente la structure de votre fichier Zip de rendu de TP MIF13.
		L'element racine est "Manifest".
		</xs:documentation>
	</xs:annotation>

	<!-- Definition des elements -->
	<xs:element name="Manifest">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Binome" type="typebinome"/>
				<xs:element name="Rapport" minOccurs="0">
				<!-- Fichier contenant soit un rapport, soit des commentaires eventuels -->
					<xs:complexType>
						<xs:attribute name="nom" type="typenomfichier" use="required" fixed="Rapport.pdf"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="Rendu" type="typedossier"/>
				<!-- Dossier contenant le travail a rendre -->
				<!-- L'attribut "nom" contient le nom du dossier racine de votre arborescence zippee (voir TP) -->
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="Dossier" type="typedossier"/>
	<xs:element name="Fichier">
		<xs:complexType>
			<xs:attribute name="nom" type="typenomfichier" use="required"/>
		</xs:complexType>
	</xs:element>

	<!-- Definition des types de contenus -->

	<xs:complexType name="typebinome">
		<xs:sequence>
			<xs:element name="Etudiant" maxOccurs="3">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Numero" type="xs:string"/>
						<xs:element name="Nom" type="xs:string"/>
						<xs:element name="Prenom" type="xs:string"/>
						<xs:element name="Groupe" type="xs:string"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="typedossier">
		<xs:sequence>
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="Dossier"/>
				<!-- Nom de chaque sous-dossier -->
			<xs:element minOccurs="0" maxOccurs="unbounded" ref="Fichier">
				<!-- Nom de chaque fichier texte rendu -->
			</xs:element>
		</xs:sequence>
		<xs:attribute name="nom" type="typenomdossier" use="required"/>
	</xs:complexType>

	<xs:simpleType name="typenomdossier">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9]*"/>
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="typenomfichier">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z0-9]*.[a-zA-Z0-9]*"/>
		</xs:restriction>
	</xs:simpleType>

</xs:schema>

=== mekdjamel/master-info-lyon1-lance-matheossian/trunk/MIF13/TP1/contenu.xml
<?xml version="1.0" encoding="UTF-8"?>
<Manifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rendu.xsd">

    <Binome>
        <Etudiant>
            <Numero>10</Numero>
            <Nom>LANCE</Nom>
            <Prenom>Florian</Prenom>
            <Groupe>Groupe 2</Groupe>
        </Etudiant>
        <Etudiant>
            <Numero>10604950</Numero>
            <Nom>MATHEOSSIAN</Nom>
            <Prenom>Dimitri</Prenom>
            <Groupe>Groupe 2</Groupe>
        </Etudiant>
    </Binome>

    <Rendu nom="TP1">
	
        <Fichier nom="Rendu.xsd" />
        <Fichier nom="contenu.xml" />
		
        <Dossier nom="XHTML">
		
			<Fichier nom="flash.html" />
			<Fichier nom="animator.swf" />
		
			<Dossier nom="CV">
				<Dossier nom="images">
					<Fichier nom="roger.jpg" />
					<Fichier nom="fond-site.jpg" />
					<Fichier nom="fond.png" />
				</Dossier>
				
				<Dossier nom="css">
					<Fichier nom="style.css" />
					<Fichier nom="cv.css" />
				</Dossier>
				
				<Fichier nom="cv.html" />
				<Fichier nom="favicon.ico" />
			</Dossier>
        </Dossier>
		
        <Dossier nom="XML">
            <Fichier nom="CV.dtd" />
            <Fichier nom="CV.xml" />
            <Fichier nom="CVETU.xml" />
            <Fichier nom="CVETU.dtd" />
        </Dossier>
		
        <Dossier nom="Schema">
            <Fichier nom="CV.xml" />
            <Fichier nom="CV.xsd" />
        </Dossier>
		
        <Dossier nom="XSL">
            <Fichier nom="CV.xml" />
            <Fichier nom="CV.xsl" />
        </Dossier>
		
        <Dossier nom="CSS">
            <Fichier nom="style.css" />
			<Fichier nom="cv.css" />
        </Dossier>
		
        <Dossier nom="Echecs">
		
            <Fichier nom="js.html" />
			
			<Dossier nom="scripts">
				<Fichier nom="Echiquier.js" />
			</Dossier>
				
			<Dossier nom="images">
				<Fichier nom="Tour_noir.png" />
				<Fichier nom="Roi_noir.png" />
				<Fichier nom="Pion_noir.png" />
				<Fichier nom="Fou_noir.png" />
				<Fichier nom="Dame_noir.png" />
				<Fichier nom="Canasson_noir.png" />
				<Fichier nom="Tour_blanc.png" />
				<Fichier nom="Roi_blanc.png" />
				<Fichier nom="Pion_blanc.png" />
				<Fichier nom="Fou_blanc.png" />
				<Fichier nom="Dame_blanc.png" />
				<Fichier nom="Canasson_blanc.png" />
			</Dossier>
			
			<Dossier nom="css">
				<Fichier nom="template.css" />
			</Dossier>
			
			<Fichier nom="svg.html" />
			
			<Dossier nom="svg">
				<Fichier nom="echecs.svg" />
			</Dossier>
			
        </Dossier>
		

    </Rendu>

</Manifest>

=== mekdjamel/master-info-lyon1-lance-matheossian/trunk/MIF13/TP4/contenu.xml
<?xml version="1.0" encoding="UTF-8"?>

<Manifest xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="rendu.xsd">

	<Binome>
	
		<Etudiant>
			<Numero>10604720</Numero>
			<Nom>LANCE</Nom>
			<Prenom>Florian</Prenom>
			<Groupe>Groupe 2</Groupe>
		</Etudiant>
		
		<Etudiant>
			<Numero>10604950</Numero>
			<Nom>MATHEOSSIAN</Nom>
			<Prenom>Dimitri</Prenom>
			<Groupe>Groupe 2</Groupe>
		</Etudiant>
		
	</Binome>
	
	<Rendu nom="TP4">
	
		<Dossier nom="ChatRoom">
		
			<Dossier nom="web">
			
				<Dossier nom="js">
					<Dossier nom="messages"></Dossier>	
						<Fichier nom="ajax.js"/>
						<Fichier nom="actions.js"/>					
				</Dossier>
				
				<Dossier nom="images">
					<Fichier nom="dialoguer.png"/>	
				</Dossier>
				
				<Dossier nom="horloge">
					<Fichier nom="horloge.svg"/>	
					<Fichier nom="horloge.jsp"/>	
				</Dossier>
				
				<Dossier nom="date">
					<Fichier nom="index.jsp"/>	
					<Fichier nom="heureXML.jsp"/>	
				</Dossier>
				
				<Dossier nom="css">
					<Fichier nom="template.css"/>	
				</Dossier>
				
				<Fichier nom="stockage.jsp"/>
				<Fichier nom="messages.jsp"/>
				<Fichier nom="connexion.html"/>
				<Fichier nom="chatRoom.jsp"/>
				
			</Dossier>
			
			<Dossier nom="test"></Dossier>
			
			<Dossier nom="src">
			
				<Dossier nom="java">
				
					<Dossier nom="Servlet">
						<Fichier nom="Deconnexion.java"/>
						<Fichier nom="Connexion.java"/>
					</Dossier>
					
					<Dossier nom="Gestion">
						<Fichier nom="Outils.java"/>
						<Fichier nom="Message.java"/>
						<Fichier nom="GestionMessages.java"/>
					</Dossier>
					
				</Dossier>
				
			</Dossier>
			
			<Dossier nom="nbproject"></Dossier>
			
			<Fichier nom="build.xml"/>
			
		</Dossier>
		
		<Fichier nom="Rendu.xsd"/>
		<Fichier nom="contenu.xml"/>
		
	</Rendu>
	
</Manifest>
